var clamp=function(a,b,c){return a<b?b:a>c?c:a},Q=Quintus().include("Sprites, Anim, Input, Touch, Scenes, UI,2D,Audio").setup({width:600,height:800}).touch().enableSound();Q.input.touchControls({controls:[["left","<"],["right",">"],[],[],[],[],["fire","a"]]});Q.controls();Q.Sprite.extend("Explosion",{init:function(a){this._super(a,{sprite:"explosion",sheet:"explosion",type:Q.SPRITE_NONE});this.add("animation");this.play("default");Q.audio.play("boom.wav")}});
Q.Sprite.extend("Heart",{init:function(a){this._super(a,{asset:"heart.png",type:Q.SPRITE_NONE});0!=Q("Heart").length?(a=Q("Heart").items[Q("Heart").length-1],this.p.x=a.p.x+this.p.w,this.p.y=a.p.y):(this.p.x=this.p.w/2,this.p.y=this.p.h/2)},step:function(a){this.p.y=this.stage.viewport.y+this.p.w}});
Q.Sprite.extend("PlayerHB",{init:function(a){a=this.createShape(a);this._super(a,{type:Q.SPRITE_FRIENDLY,x:0,y:0});this.on("hit",function(a){if(a.obj.isA("Shot")&&(a.obj.p.type&Q.SPRITE_ENEMY)==Q.SPRITE_ENEMY){var c=Q("Player").first();c.p.life--;a.obj.destroy();Q("Heart").items[Q("Heart").length-1].destroy();Q("Heart").items.splice(Q("Heart").length-1,1);0==c.p.life&&(this.destroy(),this.stage.insert(new Q.Explosion({x:c.p.x,y:c.p.y})),c.destroy(),Q.stageScene("endGame",1,{label:"You Died!"}))}})},
createShape:function(a){a=a||{};a.points=[];var b=Q("Player").first();a.points.push([-(b.p.w/2),b.p.h/2]);a.points.push([0,-b.p.h/2]);a.points.push([b.p.w/2,b.p.h/2]);return a},step:function(a){this.p.x=Q("Player").first().p.x;this.p.y=Q("Player").first().p.y;this.stage.collide(this)}});
Q.Sprite.extend("Player",{init:function(a){this._super(a,{sprite:"player",sheet:"player",x:Q.el.width/2,y:Q.el.height-60,type:Q.SPRITE_NONE,speed:10,life:5});this.add("animation");this.play("default");this.add("Gun")},step:function(a){Q.inputs.left&&(this.p.x-=this.p.speed);Q.inputs.right&&(this.p.x+=this.p.speed);Q.inputs.up&&(this.p.y-=this.p.speed);Q.inputs.down&&(this.p.y+=this.p.speed)}});
Q.Sprite.extend("Alien",{init:function(a){this._super(a,{sprite:"enemy",sheet:"enemy",x:Q.el.width/2,speed:200});this.p.y=this.p.h;this.add("animation");this.play("default");this.add("BasicAI");this.on("hit",function(a){a.obj.isA("Shot")&&(a.obj.p.type&Q.SPRITE_FRIENDLY)==Q.SPRITE_FRIENDLY&&(this.stage.insert(new Q.Explosion({x:this.p.x,y:this.p.y})),this.destroy(),a.obj.destroy(),Q.stageScene("endGame",1,{label:"You Won!"}))})},step:function(a){this.stage.collide(this)}});
Q.Sprite.extend("Shot",{init:function(a){this._super(a,{sprite:"shot",sheet:"shot",speed:200});this.add("animation");this.play("default")},step:function(a){this.p.y-=this.p.speed*a;(this.p.y>Q.el.height||0>this.p.y)&&this.destroy()}});
Q.component("BasicAI",{added:function(){this.entity.changeDirections();this.entity.on("step","move");this.entity.on("step","tryToFire");this.entity.add("Gun")},extend:{changeDirections:function(){var a=this,b=Math.floor(5*Math.random()+1);setTimeout(function(){a.p.speed=-a.p.speed;a.changeDirections()},1E3*b)},move:function(a){this.p.x-=this.p.speed*a;if(this.p.x>Q.el.width-this.p.w/2||this.p.x<0+this.p.w/2)this.p.speed=-this.p.speed},tryToFire:function(){var a=Q("Player").first();a&&a.p.x+a.p.w>
this.p.x&&a.p.x-a.p.w<this.p.x&&this.fire(Q.SPRITE_ENEMY)}}});
Q.component("Gun",{added:function(){this.entity.p.shots=[];this.entity.p.canFire=!0;this.entity.on("step","handleFiring")},extend:{handleFiring:function(a){for(a=this.p.shots.length-1;0<=a;a--)this.p.shots[a].isDestroyed&&this.p.shots.splice(a,1);Q.inputs.fire&&this.p.type==Q.SPRITE_NONE&&this.fire(Q.SPRITE_FRIENDLY)},fire:function(a){var b=this;b.p.canFire&&(a==Q.SPRITE_FRIENDLY?(a=Q.stage().insert(new Q.Shot({x:b.p.x,y:b.p.y-50,speed:200,type:Q.SPRITE_DEFAULT|Q.SPRITE_FRIENDLY})),setTimeout(function(){b.p.canFire=
!0},200)):(a=Q.stage().insert(new Q.Shot({x:b.p.x,y:b.p.y+b.p.h-20,speed:-200,type:Q.SPR|Q.SPRITE_ENEMY})),setTimeout(function(){b.p.canFire=!0},500)),b.p.shots.push(a),b.p.canFire=!1)}}});Q.scene("mainLevel",function(a){Q.gravity=0;a.insert(new Q.Repeater({asset:"cave_bg.png",speedX:1,speedY:1}));var b=a.insert(new Q.Player);a.insert(new Q.Alien);a.insert(new Q.PlayerHB);a.add("viewport").follow(b,{x:!1,y:!0});a.viewport.offset(0,300);for(i=0;i<b.p.life;i++)a.insert(new Q.Heart)});
Q.scene("endGame",function(a){var b=a.insert(new Q.UI.Container({x:Q.width/2,y:Q.height/2,fill:"#FFFFFF"})),c=b.insert(new Q.UI.Button({x:0,y:0,fill:"#CCCCCC",label:"Play Again"}));b.insert(new Q.UI.Text({x:10,y:-10-c.p.h,label:a.options.label}));c.on("click",function(){Q.clearStages();Q.stageScene("mainLevel")});b.fit(20)});
Q.load("cave_bg.png spaceship2.png shot.png alien2.png heart.png enemy.png explosion.png player.json shot.json alien.json enemy.json explosion.json boom.wav".split(" "),function(){Q.compileSheets("spaceship2.png","player.json");Q.compileSheets("enemy.png","enemy.json");Q.compileSheets("shot.png","shot.json");Q.compileSheets("alien2.png","alien.json");Q.compileSheets("explosion.png","explosion.json");Q.animations("player",{"default":{frames:[0,1,2,3],rate:.25}});Q.animations("shot",{"default":{frames:[0,
1,2,3],rate:.25}});Q.animations("alien",{"default":{frames:[0,1,2,3],rate:.25}});Q.animations("enemy",{"default":{frames:[0,1,2,3,4,5],rate:.125}});Q.animations("explosion",{"default":{frames:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24],rate:1/6,loop:!1}});Q.stageScene("mainLevel")});
